name: Build and Release Executables

permissions:
  contents: write
  
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version (e.g., v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --name "PaTaskDashboard" dashboards_with_sticks_and_circles.py

      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/PaTaskDashboard dist/PaTaskDashboard-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/PaTaskDashboard dist/PaTaskDashboard-macos
          fi
        shell: bash

      - name: Prepare Release Folder
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mkdir PaTaskDashboard-win
            mkdir PaTaskDashboard-win/task_history PaTaskDashboard-win/tasks_processes
            cp tasks_processes/* PaTaskDashboard-win/tasks_processes/
            cp example_conf.yaml PaTaskDashboard-win/
            cp example_list_of_tasks.yaml PaTaskDashboard-win/
            cp example_status_config.json PaTaskDashboard-win/
            cp example_template.json PaTaskDashboard-win/
            cp file_path_conf.yaml PaTaskDashboard-win/
            cp dist/PaTaskDashboard.exe PaTaskDashboard-win/
            zip -r PaTaskDashboard.win.zip PaTaskDashboard-win
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mkdir PaTaskDashboard-linux
            mkdir PaTaskDashboard-linux/task_history PaTaskDashboard-linux/tasks_processes
            cp tasks_processes/* PaTaskDashboard-linux/tasks_processes/
            cp example_conf.yaml PaTaskDashboard-linux/
            cp example_list_of_tasks.yaml PaTaskDashboard-linux/
            cp example_status_config.json PaTaskDashboard-linux/
            cp example_template.json PaTaskDashboard-linux/
            cp file_path_conf.yaml PaTaskDashboard-linux/
            cp dist/PaTaskDashboard-linux PaTaskDashboard-linux/
            zip -r PaTaskDashboard-linux.zip PaTaskDashboard-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mkdir PaTaskDashboard-macos
            mkdir PaTaskDashboard-macos/task_history PaTaskDashboard-macos/tasks_processes
            cp tasks_processes/* PaTaskDashboard-macos/tasks_processes/
            cp example_conf.yaml PaTaskDashboard-macos/
            cp example_list_of_tasks.yaml PaTaskDashboard-macos/
            cp example_status_config.json PaTaskDashboard-macos/
            cp example_template.json PaTaskDashboard-macos/
            cp file_path_conf.yaml PaTaskDashboard-macos/
            cp dist/PaTaskDashboard-macos PaTaskDashboard-macos/
            zip -r PaTaskDashboard-macos.zip PaTaskDashboard-macos
          fi
        shell: bash
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Make files executable (Linux/Mac)
        run: chmod +x PaTaskDash-* || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: |
            PaTaskDashboard-linux.zip
            PaTaskDashboard.win.zip
            PaTaskDashboard-macos.zip
